### ISSUE TITLE
Comms 1.0 Roadmap

### ISSUE THREAD

**Issue by sdbondi** [tari-project/tari#1009]
Tari Comms and DHT Roadmap

## TCP Connections

TCP connections are currently made with zMQ's TCP transport. There are a number of disadvantages to this approach:

1. CurveZMQ requires the public server key to be known before a secure connection can be made. This is the main reason why the current comms control service exists (which requires another open port).
2. rust-zmq is synchronous (async is possible but requires a lot of work). This results in higher resource utilization per connection and 'timeout spinning'.
3. ZMQ is designed for "all or nothing" message passing. AFAIK streaming is not possible.
4. ZMQ requires an identity frame to be sent making working with multiple peers on a single connection quite unwieldy when compared to tokio `tcp_conn.incoming().for_each(|socket| {..})`
5. Rather large c dependency which is hard to compile for mobile platforms

The following tasks seek to address these shortcomings:

- [x] Create async TCP transport using tokio TcpStream (#1044)
- [x] Investigate the work required to use async-std `TcpStream` vs tokio 
- [x] Noise protocol for over-the-wire encryption ([snow]) (#1045)
- [x] TCP socket upgrade process to enable noise protocol and multiplexing (#1046)
- [x] [Multiaddr](https://github.com/multiformats/rust-multiaddr) addresses for future-proofness (nice-to-have, existing-rust-implementation) (#1047)

## Interactive protocols 

Allow protocols to be negotiated between connected peers. A protocol refers to back and forth chatter between peers to achieve some function of the network/system. On successful negotiation of a protocol, a multiplex substream (`AsyncRead` + `AsyncWrite`) will be passed to a protocol handler that will initiate and complete the domain-level protocol. This should greatly simplify writing p2p protocols. 

- [x] Socket multiplexing ([yamux])
  - [ ] Port yamux to futures 0.3.0 (already in progress : https://github.com/paritytech/yamux) (#1048)
  - [ ] Implement multiplexing in tari (#1049)
- [x] Protocol negotiation (e.g. /tari/dan-asset/1.0 , /tari/dht-discovery/1.1, /tari/store-and-forward/0.3) (#1050)
  - [ ] Registering protocol handlers
  - [ ] Integrate the current fire and forget messaging as just another kind of protocol e.g `/tari/messaging/1.0.0` 

## Tor

Incoming connections over a mobile network (which use a [carrier-grade NAT](https://en.wikipedia.org/wiki/Carrier-grade_NAT)) are seemingly impossible. The idea here is to use Tor as a way to make mobile phones contactable through hidden services. This will also help in some cases for users behind corporate NATs and prevent having to configure residential routers. 

- [ ] Interface with Tor either natively. Creation of a hidden service should be seamless to the user. _EDIT: This is done by interfacing with the tor proxy. Specifically, the SOCKS5 port and the tor control service which has a very simple protocol allowing applications to create hidden services on-the-fly_
  - [ ] ~~Research and understand Tor protocol (https://gitweb.torproject.org/torspec.git/tree/tor-spec.txt)~~
  - [ ] ~~Take a look at Orbot and see if it would be advantageous to port it~~
  - [ ] ~~Implement (part of?) the Tor protocol~~
  - [x] Implement SOCKS5 protocol using tokio TcpStream (Done in https://github.com/tari-project/tokio-socks/tree/futures-03)
  - [x] Tor on iOS: A bundled version of the tor proxy with methods for interfacing with the Tor control port https://github.com/iCepa/Tor.framework/ 
  - [x] Tor on android: Investigate how OrBot/green wallet bundles the tor proxy for android and "borrow" that. https://github.com/Blockstream/gdk
  - [x] [If mobile doesn't do this for us] Create a rust library for interacting with the tor control port (nb `AUTHENTICATE`, `ADD_ONION` and `DEL_ONION` commands)

## Ergonomics of the public comms API

There are a number of decoupled components which work together. These should be joined to form a cohesive (and somewhat opinionated) API to enable decentralised p2p communication.

- The new "entry and exit points" for comms should be through registering protocol handlers 
- The existing tari "fire and forget/DHT" messaging protocol should be plugged into the core comms builder as any other protocol. The public api for `TariMessagingProtocol` should make setting up middleware pipelines and pubsub easy. 
- Once the lower level components are in place, it should become clearer how this would best be achieved

----

**The following are likely not needed with the use of Tor, perhaps only to enable faster non-tor communications**

## NAT traversal

NAT traversal allows nodes in a private network behind a NAT to be contactable without configuring their router/NAT to allow inbound connections on a port. This is NAT-dependent and will work in many but certainly not all network environments. This may not be needed at all if seamless Tor integration works. 

- [ ] NAT traversal 
  - [ ] Support STUN or STUN-like protocol 
  - [ ] TCP hole punching
- [ ] uPnP protocol (optional, nice-to-have)

## Relay protocol

As an alternative or in addition to NAT traversal, this feature would add the ability for base nodes to act as decentralized relays for client nodes (e.g. wallet). This would likely only be needed if inbound peer connections are not possible through Tor. 

- [ ] P2P Relay protocol

[yamux]: https://github.com/hashicorp/yamux
[snow]: https://github.com/mcginty/snow

**Comment by CjS77** [comment]
:+1:

Great overview and agree in a large part with this strategy.

## Tor

Regarding Tor, blockstream recently shipped with builtin Tor (https://github.com/Blockstream/green_android), so we can probably use the same library they did.

## Tokio

async-rs/async-std v1.0 just dropped, which has a nicer API than tokio, seems reasonably performant compared to tokio, but is not compatible with tokio :(. 

So if we're going to do a bunch of refactoring, we might want to consider jumping at some point.

**Comment by sdbondi** [comment]
@CjS77 Thanks - been wanting to dig into `async-std` - I've outlined what we/I would need to look into to use it here https://github.com/tari-project/tari/issues/1044 - luckily most libraries are independent of tokio so I suspect it shouldn't be a stretch to use it

Blockstream have a development kit (GDK) which has the tor proxy built into it and interfaces to SOCK5 proxies and the tor control port (https://github.com/Blockstream/gdk)

The tor control port has a very simple protocol which can be used with netcat

```bash
// Set ControlPort 9051 in torrc, store tor and then...

netcat localhost 9051
AUTHENTICATE
*250 OK*
ADD_ONION NEW:BEST Flags=DiscardPK Port=8080
*250-ServiceID=ddex275e53nfigag*
250 OK
*DEL_ONION ddex275e53nfigag*
250 OK
```

🎉
