### ISSUE TITLE
Pruned Mode Roadmap

### ISSUE THREAD

**Issue by sdbondi** [tari-project/tari#2040]
# Pruned Mode Roadmap

- [x] Add horizon sync state to state machine (PR #2031) 
- [x] Validate headers (PR pending)
- [x] Validate final horizon state emission (PR #2070)
- [x] Split out header sync from horizon sync (PR #2070)
- [x] Validate kernel, range proof and UTXO MMRs (PR #2070)
- [ ] ~~Download MMR hashes and validate merkle root before downloading kernels/utxos/rangeproofs~~
- [ ] Revert database to last good state on sync failure
- [ ] Header sync switching to a stronger chain
- [ ] Reduce network messages during sync
- [x] Optimise memory usage while syncing (PR #2070) 
- [x] Advertise effective pruning horizon to remote nodes (See #2005)
- [ ] Optimise bulk loading of kernels/UTXOs (Bounded-memory iterator)

**Comment by hansieodendaal** [comment]
Maybe related, so not registering a separate issue. Node could not sync from scratch with a pruning horizon set to 500. See trace logs.
[sync_from_scratch_to_horizon_500_failure.zip](https://github.com/tari-project/tari/files/4874409/sync_from_scratch_to_horizon_500_failure.zip)
