### ISSUE TITLE
Tracking issue: DNS seeds support for Tari applications

### ISSUE THREAD

**Issue by sdbondi** [tari-project/tari#2311]
Tracking issue for DNS seeds support for Tari applications.

## Tasks

- [x] Create resolver and parser for Tari seed peer DNS TXT entries (PR #2319)
- [ ] ~~tari_comms needs to be able to connect to a peer and obtain the public key given only the address~~
- [ ] DNS records and peers must be resolved on node / wallet startup (PR #2352)
- [ ] Comms integration (PR #2352)
- [ ] Allow DNS seeds to be configured from toml config (PR #2352)
- [ ] Support for DNSSEC (PR #2352)
