### ISSUE TITLE
Migrate to Rust `stable` 

### ISSUE THREAD

**Issue by delta1** [tari-project/tari#3035]
Roadmap to Rust `stable`:

* [x] Migrate Tari Bulletproofs to stable - tari-project/bulletproofs#8
* [x] Migrate Tari Crypto to stable - tari-project/tari-crypto#47
* [x] Migrate Tari Protocol to stable - in progess 
  - [x] #3034 
  - [x] #3037 
  - [x] #3056 
  - [x] zkcrypto/subtle-ng#4
  - [x] remove unstable features #3759
